using TodoClient;

Console.WriteLine("Create a new TodoItem:");

var newItem = new TodoItem
{
    Name = "Test",
    IsComplete = true
};

bool created = await new ServiceGateway().CreateItemAsync(newItem);
if (created)
    Console.WriteLine("A new TodiItem was succesfully created!");
else
    Console.WriteLine("A new TodiItem could not be created!");

Console.WriteLine("Display all TodoItems:");
var items = await new ServiceGateway().GetItemsAsync();
foreach (var item in items)
    Console.WriteLine(item.Id + ": " + item.Name + ", IsComplete: " + item.IsComplete);

if (created)
{
    Console.WriteLine("Update the newly created item:");
    newItem.Id = items.Last().Id; // Id was generated by the database when the item was created
    newItem.Name = "Test updated";
    bool updated = await new ServiceGateway().UpdateItemAsync(newItem);
    if (updated)
    {
        Console.WriteLine("Display the updated TodoItem:");
        var updatedItem = await new ServiceGateway().GetItemAsync(newItem.Id);
        Console.WriteLine(updatedItem.Id + ": " + updatedItem.Name + ", IsComplete: " + updatedItem.IsComplete);
    }
    else
        Console.WriteLine("The TodiItem could not be updated!");

    Console.WriteLine("Delete the newly created item:");
    bool deleted = await new ServiceGateway().DeleteItemAsync(newItem.Id);
    if (deleted)
        Console.WriteLine("The new TodiItem was succesfully deleted!");
    else
        Console.WriteLine("The new TodiItem could not be deleted!");
}
